<a href="https://colab.research.google.com/github/DevKumar57-67/One-Above-Intelligence/blob/main/Numpy_Tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#       NUMPY TUTORIALS

In [1]:
# Numpy is the first major AI based library in python which is heavily used in mathematical computation
# This tutorials we will explore numpy from scratch to advanced

In [2]:
# numpy download
# Use this command in your terminal or shell
!pip install numpy

In [3]:

# importing numpy with np as alias
import numpy as np

In [4]:

# An array using numpy
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:

# A 2D array using numpy
ar = np.array([[1,2],[3,4]])
print(ar)

[[1 2]
 [3 4]]


In [6]:

# shape of array
a = arr.shape
print(a)

(5,)


In [7]:
# shape of 2D array
b = arr.shape
print(a)

(5,)


In [8]:
# Performing mathematical operations
# arr+5 in all numbers
a1 = (arr+5)
print(a1)

[ 6  7  8  9 10]


In [9]:
# arr*5
a2 = (arr*5)
print(a2)

[ 5 10 15 20 25]


In [10]:

# arr /5
a3 = (arr/5)
print(a3)

[0.2 0.4 0.6 0.8 1. ]


In [11]:

# arr % 5
a4 = (arr%5)
print(a4)

[1 2 3 4 0]


In [13]:

#2D ar * 10
a5 = (ar*10)
print(a5)

[[10 20]
 [30 40]]


In [14]:
# Adding two arrays

x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

sum = x+y
print(sum)

[ 7  9 11 13 15]


In [15]:
# Multiplying two arrays

mul = x*y
print(mul)
double_mul = x**y
print(double_mul)

[ 6 14 24 36 50]
[      1     128    6561  262144 9765625]


In [16]:
# Divide the arrays

div = x/y
print(div)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [17]:
# Element wise multiplication

mat1 = np.array([[1,2,3], [4,5,6]])
mat2 = np.array([[7,8,9], [10,11,12]])

prod = (mat1 * mat2)
print(prod)

[[ 7 16 27]
 [40 55 72]]


In [18]:
# Matrix Multiplication

mat_prod = mat1 @ mat2.T
print(mat_prod)

[[ 50  68]
 [122 167]]


In [19]:
# indexing in array

z = np.array([1,2,3,4,5,6,7,8,9])
print(z[3])
print(z[5])
print(z[8])
print(z[1:4])
print(z[4:8])
print(z[4] + z[4])
print(z[2] * z[5])

4
6
9
[2 3 4]
[5 6 7 8]
10
18


In [20]:
# indexing in matrix

k = np.array([[1,2,3],[4,5,6]])
# both rows and columns
print(k[1,2])
# only columns
print(k[1])
# all rows
print(k[:2])

6
[4 5 6]
[[1 2 3]
 [4 5 6]]


#       LINEAR ALGEBRA